site_name: My Project
theme:
  name: material
plugins:
  - search
  - glightbox
  - minify:
      minify_html: true
  - mkdocs-material-extensions: footnotes
nav:
  - Home: index.md
  - API Reference: api/
